//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApps_ClientChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientChapter
    {
        public int ClientChapterSKey { get; set; }
        public string ClientID { get; set; }
        public string ChapterCode { get; set; }
        public string ChapterName { get; set; }
        public string ClientLevel1 { get; set; }
        public string ClientLevel2 { get; set; }
        public string ClientLevel3 { get; set; }
        public string ClientLevel4 { get; set; }
        public string EnvelopeLine1 { get; set; }
        public string EnvelopeLine2 { get; set; }
        public string EnvelopeLine3 { get; set; }
        public string EnvelopeLine4 { get; set; }
        public string EnvelopeLine5 { get; set; }
        public string EnvelopeClientName { get; set; }
        public string ClientAddressLine1 { get; set; }
        public string ClientAddressLine2 { get; set; }
        public string ClientAddressLine3 { get; set; }
        public string ClientCity { get; set; }
        public string ClientState { get; set; }
        public string ClientZip { get; set; }
        public string Uw { get; set; }
        public string Commander { get; set; }
        public string CommanderTitle { get; set; }
        public string BillingChapter { get; set; }
        public string AreaName { get; set; }
        public string CommanderLastName { get; set; }
        public string ClientPhone { get; set; }
        public string ClientFax { get; set; }
        public string ClientEmailAddress { get; set; }
        public string OldChapterCode { get; set; }
        public string CustomerBillingNumber { get; set; }
        public string WebAddress { get; set; }
        public string Region { get; set; }
        public Nullable<bool> Lockbox { get; set; }
        public Nullable<System.DateTime> UwBlackoutFromDate { get; set; }
        public Nullable<System.DateTime> UwBlackoutToDate { get; set; }
        public string MD_COORD { get; set; }
        public string Commander2 { get; set; }
        public string CommanderTitle2 { get; set; }
        public string CommanderLastName2 { get; set; }
        public string BillingChapter2 { get; set; }
        public string ClientEmailAddress2 { get; set; }
        public Nullable<bool> MspThank { get; set; }
        public Nullable<System.DateTime> LastThankYouDate { get; set; }
        public Nullable<bool> SeedNames { get; set; }
        public string OriginalName { get; set; }
        public string ClientName { get; set; }
        public string ChapterDesignation { get; set; }
        public string Division { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Vertical { get; set; }
        public Nullable<System.DateTime> ClientActiveDate { get; set; }
        public Nullable<System.DateTime> FiscalYearBegins { get; set; }
        public string Flex1 { get; set; }
        public string Flex2 { get; set; }
        public string Flex3 { get; set; }
        public string Flex4 { get; set; }
        public string Flex5 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
